clean code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,6 +5,14 @@ orbs:
 
 commands:
 
+    notify_on_failure:
+        steps:
+          - slack/notify:
+                event: fail
+                channel: 03-cloud-devops-eng
+                template: basic_fail_1
+
+
     destroy-environment:
         description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
         parameters:
@@ -62,7 +70,7 @@ commands:
               name: Revert migrations
               when: on_fail
               command: |
-                SUCCESS=$(curl --insecure http://kvdb.io/39exoJR7DUoEGgxKQtN9Za/migration_<< parameters.Workflow_ID >>)
+                SUCCESS=$(curl --insecure http://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
                 if(( $SUCCESS==1 )); 
                 then
                   cd ~/project/backend
@@ -72,9 +80,10 @@ commands:
 
 
 jobs:
+
     build-frontend:
         docker:
-          - image: circleci/node:13.8.0
+          - image: cimg/node:18.13.0
         steps:
           - checkout
           - restore_cache:
@@ -89,7 +98,6 @@ jobs:
                 paths: [frontend/node_modules]
                 key: frontend-build
 
-
     build-backend:
         docker:
           - image: cimg/node:18.13.0
@@ -101,15 +109,15 @@ jobs:
                 name: Back-end build
                 command: |
                   cd backend
-                  sudo npm install -g npm
-                  npm run build
+                  sudo npm install
+                  sudo npm run build
           - save_cache:
                 paths: [backend/node_modules]
                 key: backend-build
 
     test-frontend:
         docker:
-          - image: circleci/node:13.8.0
+          - image: cimg/node:18.13.0
         steps:
           - checkout
           - restore_cache:
@@ -123,7 +131,7 @@ jobs:
                   
     test-backend:
         docker:
-          - image: circleci/node:13.8.0
+          - image: cimg/node:18.13.0
         steps:
           - checkout
           - restore_cache:
@@ -135,23 +143,9 @@ jobs:
                     npm install
                     npm run test
 
-    scan-backend:
-        docker:
-          - image: circleci/node:13.8.0
-        steps:
-          - checkout
-          - restore_cache:
-                keys: [backend-build]
-          - run:
-                name: backend security scan
-                command: |
-                    cd backend
-                    npm install
-                    npm audit fix --audit-level=critical --force
-
     scan-frontend:
         docker:
-          - image: circleci/node:13.8.0
+          - image: cimg/node:18.13.0
         steps:
           - checkout
           - restore_cache:
@@ -164,10 +158,21 @@ jobs:
                     npm audit fix --force --audit-level=critical
                     npm audit fix --force --audit-level=critical
                     npm audit --audit-level=critical
-          - slack/notify:
-                channel: 03-cloud-devops-eng
-                event: fail
-                template: basic_fail_1
+          - notify_on_failure
+
+    scan-backend:
+        docker:
+          - image: cimg/node:18.13.0
+        steps:
+          - checkout
+          - restore_cache:
+                keys: [backend-build]
+          - run:
+                name: backend security scan
+                command: |
+                    cd backend
+                    npm install
+                    npm audit fix --audit-level=critical --force
 
     deploy-infrastructure:
         docker: 
@@ -219,7 +224,7 @@ jobs:
           - install_ansible
 
           - add_ssh_keys:
-                fingerprints: ["98:b9:d7:af:51:14:ec:ac:3f:ed:0f:1b:0d:7b:27:65"]
+                fingerprints: ["97:2a:b6:9b:35:49:17:e7:a1:d4:8c:a2:4e:4d:d6:1b"]
           - attach_workspace:
                 at: ~/
 
@@ -253,7 +258,7 @@ jobs:
                 command: |
                   if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
                   then
-                    curl http://kvdb.io/39exoJR7DUoEGgxKQtN9Za/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+                    curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
                   fi
 
           - destroy-environment 
@@ -273,13 +278,16 @@ jobs:
           - run:
                 name: Get backend url
                 command: |
+
                   BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
                       --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
                       --query 'Reservations[*].Instances[*].PublicIpAddress' \
                       --output text)
+
                     export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
 
                     echo "API_URL = ${API_URL}"
+
                     echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
 
                     cat frontend/.env
@@ -305,7 +313,7 @@ jobs:
           - install_nodejs
 
           - add_ssh_keys:
-                fingerprints: ["98:b9:d7:af:51:14:ec:ac:3f:ed:0f:1b:0d:7b:27:65"]
+                fingerprints: ["97:2a:b6:9b:35:49:17:e7:a1:d4:8c:a2:4e:4d:d6:1b"]
 
           - attach_workspace:
                 at: ~/
@@ -318,16 +326,20 @@ jobs:
                 command: |
                   sudo apt -y install tar gzip curl
           - run:
-                name: Deploy backend
+                name: Package backend
                 command: |
                   cd backend
                   sudo npm install
                   sudo npm run build
                   
+                  tar -czvf artifact.tar.gz dist/* package*
+
                   cd ..
-                  tar -C backend -czvf artifact.tar.gz .
-                  mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
-                  mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz                  
+                  cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files/
+
+          - run:
+                name: Deploy Backend
+                command: |
                   export TYPEORM_MIGRATIONS_DIR=./migrations
                   export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
                   export TYPEORM_MIGRATIONS=./migrations/*.ts
@@ -340,91 +352,98 @@ jobs:
           - destroy-environment
           - revert-migrations
 
-    smoke-test:
-        docker:
-          - image: cimg/node:13.8.0
-        steps:
-          # Checkout code from git
-          - checkout
-          - install_awscli
-          - install_nodejs  
+    # smoke-test:
+    #     docker:
+    #       - image: cimg/node:13.8.0
+    #     steps:
+    #       # Checkout code from git
+    #       - checkout
+    #       - install_awscli
+    #       - install_nodejs  
 
-          - run:
-                name: Backend smoke test.
-                command: |
-                  # your code here
-                  BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-                    --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
-                    --output text)
+    #       - run:
+    #             name: Backend smoke test.
+    #             command: |
+    #               # your code here
+    #               BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+    #                 --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+    #                 --query 'Reservations[*].Instances[*].PublicIpAddress' \
+    #                 --output text)
 
-                  echo ${BACKEND_PUBLIC_IP}
+    #               echo ${BACKEND_PUBLIC_IP}
 
-                  export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+    #               export API_URL=http://${BACKEND_PUBLIC_IP}:3030
                   
-                  echo ${API_URL}
+    #               echo ${API_URL}
 
-                  if curl -s --connect-timeout 10 ${API_URL}/api/status | grep -o "ok"
-                  then
-                    exit 0
-                  else
-                    exit 1
-                  fi
+    #               if curl -s --connect-timeout 10 ${API_URL}/api/status | grep -o "ok"
+    #               then
+    #                 exit 0
+    #               else
+    #                 exit 1
+    #               fi
 
-          - run:
-                name: Frontend smoke test.
-                command: |
-                  URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-                  echo ${URL} 
-                  if curl -s ${URL} | grep "Welcome"
-                  then
-                      # Change this to 0 after the job fails
-                    exit 0
-                  else
-                    exit 1
-                  fi                  
-          # - destroy-environment
-          # - revert-migrations  
+    #       - run:
+    #             name: Frontend smoke test.
+    #             command: |
+    #               URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+    #               echo ${URL} 
+    #               if curl -s ${URL} | grep "Welcome"
+    #               then
+    #                   # Change this to 0 after the job fails
+    #                 exit 0
+    #               else
+    #                 exit 1
+    #               fi                  
+    #       # - destroy-environment
+    #       # - revert-migrations  
 
-    cloudfront-update:
-        docker:
-          # Docker image here that supports AWS CLI
-          - image: cimg/node:13.8.0
-        steps:
-          # Checkout code from git
-          - checkout
-          - install_awscli
-          - install_nodejs  
-          - run: 
-                name: OLD_WORKFLOW_ID kvdb.io
-                command: |
-                  # your code here
-                  export OldworkflowID=$(aws cloudformation \
-                  list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                  --no-paginate --output text)
+    # cloudfront-update:
+    #     docker:
+    #       # Docker image here that supports AWS CLI
+    #       - image: cimg/node:13.8.0
+    #     steps:
+    #       # Checkout code from git
+    #       - checkout
+    #       - install_awscli
+    #       - install_nodejs  
+    #       - run: 
+    #             name: OLD_WORKFLOW_ID kvdb.io
+    #             command: |
+    #               # your code here
+    #               export OldworkflowID=$(aws cloudformation \
+    #               list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+    #               --no-paginate --output text)
 
-                  echo "OldWokflowID: ${OldworkflowID}"
+    #               echo "OldWokflowID: ${OldworkflowID}"
 
-                  curl https://kvdb.io/39exoJR7DUoEGgxKQtN9Za/old_workflow_id -d "${OOldworkflowID}"
-          - run:
-                name: Update cloudfront distribution
-                command: |
-                  # your code here
-                  aws cloudformation deploy \
-                  --template-file .circleci/files/cloudfront.yml \
-                  --stack-name InitialStack \
-                  --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-                  --tags project=udapeople
+    #               curl https://kvdb.io/39exoJR7DUoEGgxKQtN9Za/old_workflow_id -d "${OOldworkflowID}"
+    #       - run:
+    #             name: Update cloudfront distribution
+    #             command: |
+    #               # your code here
+    #               aws cloudformation deploy \
+    #               --template-file .circleci/files/cloudfront.yml \
+    #               --stack-name InitialStack \
+    #               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+    #               --tags project=udapeople
 
-                  echo Old Wokflow ID: "${OldworkflowID}"
+    #               echo Old Wokflow ID: "${OldworkflowID}"
 
-                  echo Current workflow Id : "${CIRCLE_WORKFLOW_ID:0:7}"
+    #               echo Current workflow Id : "${CIRCLE_WORKFLOW_ID:0:7}"
 
-          # Here's where you will add some code to rollback on failure
-          - destroy-environment
-          - revert-migrations 
+    #       # Here's where you will add some code to rollback on failure
+    #       - destroy-environment
+    #       - revert-migrations 
 
-  
+# notify_on_success:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - slack/notify:
+#             event: pass
+#             channel: 03-cloud-devops-eng
+#             template: success_tagged_deployment_1  
 
 
 workflows:
@@ -454,8 +473,8 @@ workflows:
                 requires: [run-migrations]
           - deploy-backend:
                 requires: [run-migrations]
-          - smoke-test:
-              requires: [deploy-backend, deploy-frontend]
-          - cloudfront-update:
-                requires: [smoke-test]
+          # - smoke-test:
+          #     requires: [deploy-backend, deploy-frontend]
+          # - cloudfront-update:
+          #       requires: [smoke-test]
 
