smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -355,49 +355,49 @@ jobs:
           - destroy-environment
           - revert-migrations
 
-    # smoke-test:
-    #     docker:
-    #       - image: cimg/node:13.8.0
-    #     steps:
-    #       # Checkout code from git
-    #       - checkout
-    #       - install_awscli
-    #       - install_nodejs  
+    smoke-test:
+        docker:
+          - image: cimg/node:13.8.0
+        steps:
+          # Checkout code from git
+          - checkout
+          - install_awscli
+          - install_nodejs  
 
-    #       - run:
-    #             name: Backend smoke test.
-    #             command: |
-    #               # your code here
-    #               BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-    #                 --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-    #                 --query 'Reservations[*].Instances[*].PublicIpAddress' \
-    #                 --output text)
+          - run:
+                name: Backend smoke test.
+                command: |
+                  # your code here
+                  BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                    --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                    --output text)
 
-    #               echo ${BACKEND_PUBLIC_IP}
+                  echo ${BACKEND_PUBLIC_IP}
 
-    #               export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+                  export API_URL=http://${BACKEND_PUBLIC_IP}:3030
                   
-    #               echo ${API_URL}
+                  echo ${API_URL}
 
-    #               if curl -s --connect-timeout 10 ${API_URL}/api/status | grep -o "ok"
-    #               then
-    #                 exit 0
-    #               else
-    #                 exit 1
-    #               fi
+                  if curl -s --connect-timeout 10 ${API_URL}/api/status | grep -o "ok"
+                  then
+                    exit 0
+                  else
+                    exit 1
+                  fi
 
-    #       - run:
-    #             name: Frontend smoke test.
-    #             command: |
-    #               URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-    #               echo ${URL} 
-    #               if curl -s ${URL} | grep "Welcome"
-    #               then
-    #                   # Change this to 0 after the job fails
-    #                 exit 0
-    #               else
-    #                 exit 1
-    #               fi                  
+          - run:
+                name: Frontend smoke test.
+                command: |
+                  URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+                  echo ${URL} 
+                  if curl -s ${URL} | grep "Welcome"
+                  then
+                      # Change this to 0 after the job fails
+                    exit 0
+                  else
+                    exit 1
+                  fi                  
     #       # - destroy-environment
     #       # - revert-migrations  
 
@@ -476,8 +476,8 @@ workflows:
                 requires: [run-migrations]
           - deploy-backend:
                 requires: [run-migrations]
-          # - smoke-test:
-          #     requires: [deploy-backend, deploy-frontend]
+          - smoke-test:
+              requires: [deploy-backend, deploy-frontend]
           # - cloudfront-update:
           #       requires: [smoke-test]
 
