smoke test re-run

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -336,45 +336,45 @@ jobs:
           - destroy-environment
           - revert-migrations
 
-    # smoke-test:
-    #     docker:
-    #       - image: cimg/base:stable
-    #     steps:
-    #       # Checkout code from git
-    #       - checkout
-    #       - install_awscli
-    #       - install_nodejs  
+    smoke-test:
+        docker:
+          - image: cimg/base:stable
+        steps:
+          # Checkout code from git
+          - checkout
+          - install_awscli
+          - install_nodejs  
 
-    #       - run:
-    #             name: Backend smoke test.
-    #             command: |
-    #               # your code here
-    #               BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-    #                 --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-    #                 --query 'Reservations[*].Instances[*].PublicIpAddress' \
-    #                 --output text)
-    #               export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-    #               if curl "${API_URL}/api/status" | grep "ok"
-    #               then
-    #                   exit 0
-    #               else
-    #                   exit 1
-    #               fi
+          - run:
+                name: Backend smoke test.
+                command: |
+                  # your code here
+                  BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                    --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                    --output text)
+                  export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+                  if curl "${API_URL}/api/status" | grep "ok"
+                  then
+                      exit 0
+                  else
+                      exit 1
+                  fi
 
-    #       - run:
-    #             name: Frontend smoke test.
-    #             command: |
-    #               URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-    #               echo ${URL} 
-    #               if curl -s ${URL} | grep "Welcome"
-    #               then
-    #                   # Change this to 0 after the job fails
-    #                 exit 1
-    #               else
-    #                 exit 1
-    #               fi                  
-    #       - destroy-environment
-    #       - revert-migrations  
+          - run:
+                name: Frontend smoke test.
+                command: |
+                  URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+                  echo ${URL} 
+                  if curl -s ${URL} | grep "Welcome"
+                  then
+                      # Change this to 0 after the job fails
+                    exit 1
+                  else
+                    exit 1
+                  fi                  
+          - destroy-environment
+          - revert-migrations  
     
 
 
@@ -405,6 +405,6 @@ workflows:
                 requires: [run-migrations]
           - deploy-backend:
                 requires: [run-migrations]
-          # - smoke-test:
-          #     requires: [deploy-backend, deploy-frontend]
+          - smoke-test:
+              requires: [deploy-backend, deploy-frontend]
 
